apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      containers:
        - name: project
          image: gcr.io/PROJECT_ID/IMAGE-backend
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-db-pass
                  key: POSTGRES_PASSWORD
            - name: PGUSER
              value: "postgres"
            - name: PGDATABASE
              value: "postgres"
            - name: PGHOST
              value: "project-db-svc"
            - name: PGPORT
              value: "5432"
