apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
  namespace: applications
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gke-pvc
      containers:
        - name: postgres
          image: postgres:13.0
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-pass
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
