apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: thefenix/dok-ping-pong:0.5.1
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10 
            httpGet:
              path: /databaseready
              port: 80
          envFrom:
            - secretRef:
                name: postgres-pass
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: POSTGRES_PASSWORD
            - name: PGUSER
              value: "postgres"
            - name: PGDATABASE
              value: "postgres"
            - name: PGHOST
              value: "postgres-svc"
            - name: PGPORT
              value: "5432"
