apiVersion: batch/v1
kind: CronJob
metadata:
  name: project-cronjob
  namespace: project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-task
            image: thefenix/dok-project-dailytask:0.1.3
            resources:
              limits:
                cpu: "100m"
                memory: "256Mi"
          restartPolicy: OnFailure
