apiVersion: batch/v1
kind: CronJob
metadata:
  name: project-cronjob
  namespace: project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-task
            image: gcr.io/PROJECT_ID/IMAGE-cronjob
          restartPolicy: OnFailure
