apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: log-output-split-vol
        emptyDir: {}
      containers:
      - name: log-output
        image: thefenix/dok-log-output:0.8
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10 
          httpGet:
            path: /ready
            port: 80
        envFrom:
        - configMapRef:
            name: log-output-cfgmap
        volumeMounts:
        - name: log-output-split-vol
          mountPath: /usr/src/app/files
      - name: log-output-writer
        image: thefenix/dok-log-output-writer:0.1
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
        volumeMounts:
        - name: log-output-split-vol
          mountPath: /usr/src/app/files
