apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-split-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-split
  template:
    metadata:
      labels:
        app: log-output-split
    spec:
      volumes:
        - name: log-output-split-vol
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: thefenix/dok-log-output-writer:0.1
          volumeMounts:
          - name: log-output-split-vol
            mountPath: /usr/src/app/files
        - name: log-output-reader
          image: thefenix/dok-log-output-reader:0.1
          volumeMounts:
          - name: log-output-split-vol
            mountPath: /usr/src/app/files
