apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
  namespace: project
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 10m
    successCondition: result < 0.75
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1657-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
        query: |
          scalar(
            sum(rate(container_cpu_user_seconds_total{namespace="project"}[10m]) * 100)
          )