apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - ./namespace.yaml
  - frontend/manifests/persistentvolumeclaim.yaml
  - frontend/manifests/deployment.yaml
  - frontend/manifests/service.yaml
  - backend/manifests/secret.enc.yaml
  - backend/manifests/persistentvolumeclaim.yaml
  - backend/manifests/db-statefulset.yaml
  - backend/manifests/db-service.yaml
  - backend/manifests/deployment.yaml
  - backend/manifests/service.yaml
  - backend/manifests/ingress.yaml
  - cronjob/manifests/cronjob.yaml
  - broadcaster/manifests/deployment.yaml
  - broadcaster/manifests/secret.enc.yaml
images:
- name: BACKEND_IMAGE
  newName: thefenix/dok-project-backend
  newTag: 8eca65872df371ce5813e487bd240fccb53ce15a
- name: BROADCASTER_IMAGE
  newName: thefenix/dok-project-broadcaster
  newTag: 8eca65872df371ce5813e487bd240fccb53ce15a
- name: CRONJOB_IMAGE
  newName: thefenix/dok-project-dailytask
  newTag: 8eca65872df371ce5813e487bd240fccb53ce15a
- name: FRONTEND_IMAGE
  newName: thefenix/dok-project
  newTag: 8eca65872df371ce5813e487bd240fccb53ce15a
