apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - ./namespace.yaml
  - frontend/manifests/persistentvolumeclaim.yaml
  - frontend/manifests/deployment.yaml
  - frontend/manifests/service.yaml
  - backend/manifests/secret.yaml
  - backend/manifests/persistentvolumeclaim.yaml
  - backend/manifests/db-statefulset.yaml
  - backend/manifests/db-service.yaml
  - backend/manifests/deployment.yaml
  - backend/manifests/service.yaml
  - backend/manifests/ingress.yaml
  - cronjob/manifests/cronjob.yaml
  - broadcaster/manifests/deployment.yaml
  - broadcaster/manifests/secret.yaml
