apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend/manifests/persistentvolumeclaim.yaml
  - frontend/manifests/deployment.yaml
  - frontend/manifests/service.yaml
  - backend/manifests/secret.yaml
  - backend/manifests/persistentvolumeclaim.yaml
  - backend/manifests/db-statefulset.yaml
  - backend/manifests/db-service.yaml
  - backend/manifests/deployment.yaml
  - backend/manifests/service.yaml
  - backend/manifests/ingress.yaml
