apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
      - name: project-volume
        persistentVolumeClaim:
          claimName: project-claim
      containers:
        - name: project
          image: thefenix/dok-project:1.0
          volumeMounts:
          - name: project-volume
            mountPath: /usr/src/app/files